learning_log/urls.py
from django.urls import include, path

urlpatterns = [
    path('',include('learning_logs.urls')),
    
]

learning_logs/urls.py
"""Defines URL patterns for learning_logs."""

from django.urls import path
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

app_name= 'learning_logs'

urlpatterns = [
    #Home page
    path('',views.index, name='index'),
        
    path('exercises', views.exercises, name='exercises'),

    path('about',views.about, name='about'),
    
    path('exer1',views.exer1, name='exer1'),
    
    path('exer2',views.exer2, name='exer2'),

    path('exer3',views.exer3, name='exer3'),

    path('exer5',views.exer5, name='exer5'),

    path('exer6',views.exer6, name='exer6'),

    path('exer7',views.exer7, name='exer7'),

    path('exer8',views.exer8, name='exer8'),
    
    path('exer9',views.exer9, name='exer9'),
    
    path('exer10',views.exer10, name='exer10'),
        
]

urlpatterns += staticfiles_urlpatterns()

learning_logs/views.py
from ast import Return
from django.shortcuts import render



def index(request):
    """Home Page"""
    return render(request, 'learning_logs/index.html',)

def exercises(request):
    """About student page"""
    return render(request, 'learning_logs/exercises.html',)

def about(request):
    """exercises [age"""
    return render(request, 'learning_logs/about.html' )

def exer1(request):
    """exercise 1 page"""
    return render(request, 'learning_logs/exer1.html')

def exer2(request):
    """exercise 2 page"""
    return render(request, 'learning_logs/exer2.html')

def exer3(request):
    """exercise 3 page"""
    return render(request, 'learning_logs/exer3.html')

def exer5(request):
    """exercise 5 page"""
    return render(request, 'learning_logs/exer5.html')

def exer6(request):
    """exercise 6 page"""
    return render(request, 'learning_logs/exer6.html')

def exer7(request):
    """exercise 7 page"""
    return render(request, 'learning_logs/exer7.html')

def exer8(request):
    """exercise 8 page"""
    return render(request, 'learning_logs/exer8.html')

def exer9(request):
    """exercise 9 page"""
    return render(request, 'learning_logs/exer9.html')

def exer10(request):
    """exercise 10 page"""
    return render(request, 'learning_logs/exer10.html')



    

learning_logs/templates/learning_logs/about.html
{% extends "learning_logs/index.html" %}

{% block content %}

{% load static %}
<!-- Add icon library -->
<div class="card">
    <img src= "{% static 'learning_logs/media/Id.jpg' %}"  alt="Ed Mikael" style="width:10%">
  <h1>Ed Mikael V. Bebic</h1>
  <p class="title">UBLC</p>
  <p>Class Section: CPE2A</p>
  <p>Year 2021-2022</p>
  <p>Birth: 03/15/02</p>
  <p>Age: 20</p>
  <p>Address: Purok 4 Lipa Batangas</p>
</div>

{% endblock content %}

learning_logs/templates/learning_logs/exer1.html
{% extends "learning_logs/index.html" %}

{% block content %}
<h2> #1</h2>

<h3> Introduction to Python </h3>
<a href= "{% url 'learning_logs:exer10' %}">Back</a>
<a href= "{% url 'learning_logs:exer2' %}">Next</a>
<iframe src="https://trinket.io/embed/python/0aa9b9272b" width="100%" height="356" frameborder="0" marginwidth="0" marginheight="0" allowfullscreen></iframe>

{% endblock content %}

learning_logs/templates/learning_logs/exer10.html
{% extends "learning_logs/index.html" %}

{% block content %}
<h2> #10</h2>

<h2> Python - Functions </h2/>
    <a href= "{% url 'learning_logs:exer9' %}">Back</a>
    <a href= "{% url 'learning_logs:exer1' %}">Next</a>
    <iframe src="https://trinket.io/embed/python/c97cabb510" width="100%" height="356" frameborder="0" marginwidth="0" marginheight="0" allowfullscreen></iframe>

{% endblock content %}

learning_logs/templates/learning_logs/exer2.html
{% extends "learning_logs/index.html" %}

{% block content %}
<h2> #2</h2>
<h3> Python - Variables and strings </h3>
<a href= "{% url 'learning_logs:exer1' %}">Back</a>
<a href= "{% url 'learning_logs:exer3' %}">Next</a>

<iframe src="https://trinket.io/embed/python/04511acfbc" width="100%" height="356" frameborder="0" marginwidth="0" marginheight="0" allowfullscreen></iframe>



{% endblock content %}

learning_logs/templates/learning_logs/exer3.html
{% extends "learning_logs/index.html" %}

{% block content %}
<h2> #3 & 4</h2>

<h3> Python - Fundamentals and If Statements</h3>
<a href= "{% url 'learning_logs:exer2' %}">Back</a>
<a href= "{% url 'learning_logs:exer5' %}">Next</a>

<iframe src="https://trinket.io/embed/python/79745dd764" width="100%" height="356" frameborder="0" marginwidth="0" marginheight="0" allowfullscreen></iframe>

{% endblock content %}

learning_logs/templates/learning_logs/exer5.html
{% extends "learning_logs/index.html" %}

{% block content %}
<h2> #5</h2>

<h2> Python - While Loop </h2/>
    <a href= "{% url 'learning_logs:exer3' %}">Back</a>
    <a href= "{% url 'learning_logs:exer6' %}">Next</a>

    <iframe src="https://trinket.io/embed/python/d9b063d9ef" width="100%" height="356" frameborder="0" marginwidth="0" marginheight="0" allowfullscreen></iframe>

{% endblock content %}

learning_logs/templates/learning_logs/exer6.html
{% extends "learning_logs/index.html" %}

{% block content %}
<h2> #6</h2>

<h2> Python - List </h2/>
    <a href= "{% url 'learning_logs:exer5' %}">Back</a>
    <a href= "{% url 'learning_logs:exer7' %}">Next</a>
    <iframe src="https://trinket.io/embed/python/9e83d77059" width="100%" height="356" frameborder="0" marginwidth="0" marginheight="0" allowfullscreen></iframe>

{% endblock content %}

learning_logs/templates/learning_logs/exer7.html
{% extends "learning_logs/index.html" %}

{% block content %}
<h2> #7</h2>

<h2> Python - Tuples </h2/>
    <a href= "{% url 'learning_logs:exer6' %}">Back</a>
    <a href= "{% url 'learning_logs:exer8' %}">Next</a>
<iframe src="https://trinket.io/embed/python/fafee2b6d3" width="100%" height="356" frameborder="0" marginwidth="0" marginheight="0" allowfullscreen></iframe>

{% endblock content %}

learning_logs/templates/learning_logs/exer8.html
{% extends "learning_logs/index.html" %}

{% block content %}
<h2> #8</h2>

<h2> The Programming Language used in this Section is Python </h2/>
    <a href= "{% url 'learning_logs:exer7' %}">Back</a>
    <a href= "{% url 'learning_logs:exer9' %}">Next</a>

    <iframe src="https://trinket.io/embed/python/1fdeaef7db" width="100%" height="356" frameborder="0" marginwidth="0" marginheight="0" allowfullscreen></iframe>
    <iframe src="https://trinket.io/embed/python/25a3c9352f" width="100%" height="356" frameborder="0" marginwidth="0" marginheight="0" allowfullscreen></iframe>
    <iframe src="https://trinket.io/embed/python/9feb711868" width="100%" height="356" frameborder="0" marginwidth="0" marginheight="0" allowfullscreen></iframe>
    <iframe src="https://trinket.io/embed/python/0540b92ace" width="100%" height="356" frameborder="0" marginwidth="0" marginheight="0" allowfullscreen></iframe>
{% endblock content %}

learning_logs/templates/learning_logs/exer9.html
{% extends "learning_logs/index.html" %}

{% block content %}
<h2> #9</h2>

<h2> Python - Dictionaries </h2/>
    <a href= "{% url 'learning_logs:exer8' %}">Back</a>
    <a href= "{% url 'learning_logs:exer10' %}">Next</a>

    <iframe src="https://trinket.io/embed/python/2e69cbeb76" width="100%" height="356" frameborder="0" marginwidth="0" marginheight="0" allowfullscreen></iframe>

{% endblock content %}

learning_logs/templates/learning_logs/exercises.html
{% extends "learning_logs/index.html" %}

{% block header %}
{% endblock header %}

{% block content %}
<h2> The Programming Language used in this Section is Python </h2/>

    <p><h3><a href= "{% url 'learning_logs:exer1' %}">Execises #1</a></h3></p>
    <p><h3><a href= "{% url 'learning_logs:exer2' %}">Execises #2</a></h3></p>
    <p><h3><a href= "{% url 'learning_logs:exer3' %}">Execises #3 & 4</a></h3></p>
    <p><h3><a href= "{% url 'learning_logs:exer5' %}">Execises #5</a></h3></p>
    <p><h3><a href= "{% url 'learning_logs:exer6' %}">Execises #6</a></h3></p>
    <p><h3><a href= "{% url 'learning_logs:exer7' %}">Execises #7</a></h3></p>
    <p><h3><a href= "{% url 'learning_logs:exer8' %}">Execises #8</a></h3></p>
    <p><h3><a href= "{% url 'learning_logs:exer9' %}">Execises #9</a></h3></p>
    <p><h3><a href= "{% url 'learning_logs:exer10' %}">Execises #10</a></h3></p>
   
{% endblock content %}

learning_logs/templates/learning_logs/index.html
<body style="background-color:white;">
  <!DOCTYPE html>
  <html lang="en">
  <head>
  <title>Completion Site</title>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <style>
 
  body {
    font-family: Arial;
    margin: 0;
  }
  
  /* Header/Logo Title */
  .header {
    padding: 60px;
    text-align: center;
    background: #1abc9c;
    color: white;
    font-size: 30px;
  }
  
  /* Page Content */
  .content {padding:20px;}
  </style>
  </head>
  <body>
  
  <div class="header">
    <h1>Completion</h1>
    <p><!-- Navigation -->
      <nav>
        <h1>
        <a href= "{% url 'learning_logs:index' %}">Home</a>
      
        <a href= "{% url 'learning_logs:exercises' %}">Exercises</a>
      
        <a href= "{% url 'learning_logs:about' %}">About Student</a>
        </h1>
      </nav>
      </body>
      </p>
  </div>
  
  <div class="content">
    
  </div>
  
  </body>
  </html>
  

{% block content %}

<!DOCTYPE html>
{% load static %}
<html>
<body>


<h2>Learn about OOP</h2>

<div class="w3-content w3-display-container">
  <img class="Slide" src="{% static 'learning_logs/media/slide1.jpg' %}" style="width:80%">
  <img class="Slide" src="{% static 'learning_logs/media/slide2.jpg' %}" style="width:80%">
  <img class="Slide" src="{% static 'learning_logs/media/slide3.jpg' %}" style="width:80%">
  <img class="Slide" src="{% static 'learning_logs/media/slide4.jpg' %}" style="width:80%">
  <img class="Slide" src="{% static 'learning_logs/media/slide5.jpg' %}" style="width:80%">
  <img class="Slide" src="{% static 'learning_logs/media/slide6.jpg' %}" style="width:80%">
  <img class="Slide" src="{% static 'learning_logs/media/slide7.jpg' %}" style="width:80%">
  <img class="Slide" src="{% static 'learning_logs/media/slide8.jpg' %}" style="width:80%">
  <img class="Slide" src="{% static 'learning_logs/media/slide9.jpg' %}" style="width:80%">

  

  <button class="left" onclick="plusDivs(-1)">&#10094;</button>
  <button class="right" onclick="plusDivs(1)">&#10095;</button>
</div>

<script>
var slideIndex = 1;
showDivs(slideIndex);

function plusDivs(n) {
  showDivs(slideIndex += n);
}

function showDivs(n) {
  var i;
  var x = document.getElementsByClassName("Slide");
  if (n > x.length) {slideIndex = 1}
  if (n < 1) {slideIndex = x.length}
  for (i = 0; i < x.length; i++) {
    x[i].style.display = "none";  
  }
  x[slideIndex-1].style.display = "block";  
}
</script>
</body>
</html>


{% endblock content %}